export default [
    { id: 1, nome: 'Brasil' },
    { id: 2, nome: 'Argentina' },
    { id: 3, nome: 'Japão' },
    { id: 4, nome: 'França' },
    { id: 5, nome: 'China' },
    { id: 7, nome: 'Angola' },
    { id: 8, nome: 'Egito' },
    { id: 9, nome: 'Espanha' },
    { id: 10, nome: 'Portugal' },
    { id: 11, nome: 'Canadá' },
    { id: 12, nome: 'Iraque' },
    { id: 13, nome: 'México' },
    { id: 14, nome: 'Iraque' },
    { id: 15, nome: 'Peru' },
    { id: 16, nome: 'Qatar' },
    { id: 17, nome: 'Rússia' },
    { id: 18, nome: 'Tailândia' },
    { id: 19, nome: 'Síria' },
    { id: 20, nome: 'África do Sul' },
]
